production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 107.170.49.159
    port: 8983
    log_level: INFO
    solr_home: solr

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test