production:
  solr:
    hostname: 107.170.49.159
    port: 8983
    log_level: INFO
    solr_home: solr
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 107.170.49.159
    port: 8983
    log_level: INFO
    solr_home: solr
  # solr:
  #   hostname: localhost
  #   port: 8982
  #   log_level: INFO
  #   path: /solr/default
  #   solr_home: solr
  # auto_commit_after_request: false

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    